version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seizure
      POSTGRES_DB: bewis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
volumes:
  postgres_data:

networks:
  backend:
    driver: bridge